name: finance_manager
description: "Track expenses, manage budgets, and achieve financial goals easily."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  file_picker: ^10.1.1
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.0
  path: ^1.9.1
  easy_image_viewer: ^1.5.1
  google_mobile_ads: ^6.0.0
dev_dependencies:
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
flutter_native_splash:
  color: "#212121"
  image: assets/logo.png
  android_12:
    color: "#212121"
  android: true
  ios: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
