class Currency {
  final String name;
  final String symbol;
  final String country;

  Currency({required this.name, required this.symbol, required this.country});
}

// Map of currency codes to their details
final Map<String, Currency> currencies = {
  'AED': Currency(
    name: 'UAE Dirham',
    symbol: 'د.إ',
    country: 'United Arab Emirates',
  ),
  'AFN': Currency(name: 'Afghan Afghani', symbol: '؋', country: 'Afghanistan'),
  'ALL': Currency(name: 'Albanian Lek', symbol: 'L', country: 'Albania'),
  'AMD': Currency(name: 'Armenian Dram', symbol: '֏', country: 'Armenia'),
  'ANG': Currency(
    name: 'Netherlands Antillian Guilder',
    symbol: 'ƒ',
    country: 'Netherlands Antilles',
  ),
  'AOA': Currency(name: 'Angolan Kwanza', symbol: 'Kz', country: 'Angola'),
  'ARS': Currency(name: 'Argentine Peso', symbol: '\$', country: 'Argentina'),
  'AUD': Currency(
    name: 'Australian Dollar',
    symbol: 'A\$',
    country: 'Australia',
  ),
  'AWG': Currency(name: 'Aruban Florin', symbol: 'ƒ', country: 'Aruba'),
  'AZN': Currency(
    name: 'Azerbaijani Manat',
    symbol: '₼',
    country: 'Azerbaijan',
  ),
  'BAM': Currency(
    name: 'Bosnia and Herzegovina Mark',
    symbol: 'KM',
    country: 'Bosnia and Herzegovina',
  ),
  'BBD': Currency(name: 'Barbados Dollar', symbol: '\$', country: 'Barbados'),
  'BDT': Currency(name: 'Bangladeshi Taka', symbol: '৳', country: 'Bangladesh'),
  'BGN': Currency(name: 'Bulgarian Lev', symbol: 'лв', country: 'Bulgaria'),
  'BHD': Currency(name: 'Bahraini Dinar', symbol: '.د.ب', country: 'Bahrain'),
  'BIF': Currency(name: 'Burundian Franc', symbol: 'Fr', country: 'Burundi'),
  'BMD': Currency(name: 'Bermudian Dollar', symbol: '\$', country: 'Bermuda'),
  'BND': Currency(name: 'Brunei Dollar', symbol: '\$', country: 'Brunei'),
  'BOB': Currency(
    name: 'Bolivian Boliviano',
    symbol: 'Bs.',
    country: 'Bolivia',
  ),
  'BRL': Currency(name: 'Brazilian Real', symbol: 'R\$', country: 'Brazil'),
  'BSD': Currency(name: 'Bahamian Dollar', symbol: '\$', country: 'Bahamas'),
  'BTN': Currency(name: 'Bhutanese Ngultrum', symbol: 'Nu.', country: 'Bhutan'),
  'BWP': Currency(name: 'Botswana Pula', symbol: 'P', country: 'Botswana'),
  'BYN': Currency(name: 'Belarusian Ruble', symbol: 'Br', country: 'Belarus'),
  'BZD': Currency(name: 'Belize Dollar', symbol: '\$', country: 'Belize'),
  'CAD': Currency(name: 'Canadian Dollar', symbol: 'C\$', country: 'Canada'),
  'CDF': Currency(
    name: 'Congolese Franc',
    symbol: 'Fr',
    country: 'Democratic Republic of the Congo',
  ),
  'CHF': Currency(name: 'Swiss Franc', symbol: 'Fr', country: 'Switzerland'),
  'CLP': Currency(name: 'Chilean Peso', symbol: '\$', country: 'Chile'),
  'CNY': Currency(name: 'Chinese Renminbi', symbol: '¥', country: 'China'),
  'COP': Currency(name: 'Colombian Peso', symbol: '\$', country: 'Colombia'),
  'CRC': Currency(
    name: 'Costa Rican Colon',
    symbol: '₡',
    country: 'Costa Rica',
  ),
  'CUP': Currency(name: 'Cuban Peso', symbol: '\$', country: 'Cuba'),
  'CVE': Currency(
    name: 'Cape Verdean Escudo',
    symbol: '\$',
    country: 'Cape Verde',
  ),
  'CZK': Currency(
    name: 'Czech Koruna',
    symbol: 'Kč',
    country: 'Czech Republic',
  ),
  'DJF': Currency(name: 'Djiboutian Franc', symbol: 'Fr', country: 'Djibouti'),
  'DKK': Currency(name: 'Danish Krone', symbol: 'kr', country: 'Denmark'),
  'DOP': Currency(
    name: 'Dominican Peso',
    symbol: '\$',
    country: 'Dominican Republic',
  ),
  'DZD': Currency(name: 'Algerian Dinar', symbol: 'د.ج', country: 'Algeria'),
  'EGP': Currency(name: 'Egyptian Pound', symbol: '£', country: 'Egypt'),
  'ERN': Currency(name: 'Eritrean Nakfa', symbol: 'Nfk', country: 'Eritrea'),
  'ETB': Currency(name: 'Ethiopian Birr', symbol: 'Br', country: 'Ethiopia'),
  'EUR': Currency(name: 'Euro', symbol: '€', country: 'European Union'),
  'FJD': Currency(name: 'Fiji Dollar', symbol: '\$', country: 'Fiji'),
  'FKP': Currency(
    name: 'Falkland Islands Pound',
    symbol: '£',
    country: 'Falkland Islands',
  ),
  'FOK': Currency(
    name: 'Faroese Króna',
    symbol: 'kr',
    country: 'Faroe Islands',
  ),
  'GBP': Currency(
    name: 'Pound Sterling',
    symbol: '£',
    country: 'United Kingdom',
  ),
  'GEL': Currency(name: 'Georgian Lari', symbol: '₾', country: 'Georgia'),
  'GGP': Currency(name: 'Guernsey Pound', symbol: '£', country: 'Guernsey'),
  'GHS': Currency(name: 'Ghanaian Cedi', symbol: '₵', country: 'Ghana'),
  'GIP': Currency(name: 'Gibraltar Pound', symbol: '£', country: 'Gibraltar'),
  'GMD': Currency(name: 'Gambian Dalasi', symbol: 'D', country: 'The Gambia'),
  'GNF': Currency(name: 'Guinean Franc', symbol: 'Fr', country: 'Guinea'),
  'GTQ': Currency(
    name: 'Guatemalan Quetzal',
    symbol: 'Q',
    country: 'Guatemala',
  ),
  'GYD': Currency(name: 'Guyanese Dollar', symbol: '\$', country: 'Guyana'),
  'HKD': Currency(
    name: 'Hong Kong Dollar',
    symbol: 'HK\$',
    country: 'Hong Kong',
  ),
  'HNL': Currency(name: 'Honduran Lempira', symbol: 'L', country: 'Honduras'),
  'HRK': Currency(name: 'Croatian Kuna', symbol: 'kn', country: 'Croatia'),
  'HTG': Currency(name: 'Haitian Gourde', symbol: 'G', country: 'Haiti'),
  'HUF': Currency(name: 'Hungarian Forint', symbol: 'Ft', country: 'Hungary'),
  'IDR': Currency(
    name: 'Indonesian Rupiah',
    symbol: 'Rp',
    country: 'Indonesia',
  ),
  'ILS': Currency(name: 'Israeli New Shekel', symbol: '₪', country: 'Israel'),
  'IMP': Currency(name: 'Manx Pound', symbol: '£', country: 'Isle of Man'),
  'INR': Currency(name: 'Indian Rupee', symbol: '₹', country: 'India'),
  'IQD': Currency(name: 'Iraqi Dinar', symbol: 'ع.د', country: 'Iraq'),
  'IRR': Currency(name: 'Iranian Rial', symbol: '﷼', country: 'Iran'),
  'ISK': Currency(name: 'Icelandic Króna', symbol: 'kr', country: 'Iceland'),
  'JEP': Currency(name: 'Jersey Pound', symbol: '£', country: 'Jersey'),
  'JMD': Currency(name: 'Jamaican Dollar', symbol: 'J\$', country: 'Jamaica'),
  'JOD': Currency(name: 'Jordanian Dinar', symbol: 'د.ا', country: 'Jordan'),
  'JPY': Currency(name: 'Japanese Yen', symbol: '¥', country: 'Japan'),
  'KES': Currency(name: 'Kenyan Shilling', symbol: 'Sh', country: 'Kenya'),
  'KGS': Currency(name: 'Kyrgyzstani Som', symbol: 'с', country: 'Kyrgyzstan'),
  'KHR': Currency(name: 'Cambodian Riel', symbol: '៛', country: 'Cambodia'),
  'KID': Currency(name: 'Kiribati Dollar', symbol: '\$', country: 'Kiribati'),
  'KMF': Currency(name: 'Comorian Franc', symbol: 'Fr', country: 'Comoros'),
  'KRW': Currency(
    name: 'South Korean Won',
    symbol: '₩',
    country: 'South Korea',
  ),
  'KWD': Currency(name: 'Kuwaiti Dinar', symbol: 'د.ك', country: 'Kuwait'),
  'KYD': Currency(
    name: 'Cayman Islands Dollar',
    symbol: '\$',
    country: 'Cayman Islands',
  ),
  'KZT': Currency(
    name: 'Kazakhstani Tenge',
    symbol: '₸',
    country: 'Kazakhstan',
  ),
  'LAK': Currency(name: 'Lao Kip', symbol: '₭', country: 'Laos'),
  'LBP': Currency(name: 'Lebanese Pound', symbol: 'ل.ل', country: 'Lebanon'),
  'LKR': Currency(name: 'Sri Lanka Rupee', symbol: 'Rs', country: 'Sri Lanka'),
  'LRD': Currency(name: 'Liberian Dollar', symbol: '\$', country: 'Liberia'),
  'LSL': Currency(name: 'Lesotho Loti', symbol: 'L', country: 'Lesotho'),
  'LYD': Currency(name: 'Libyan Dinar', symbol: 'ل.د', country: 'Libya'),
  'MAD': Currency(name: 'Moroccan Dirham', symbol: 'د.م.', country: 'Morocco'),
  'MDL': Currency(name: 'Moldovan Leu', symbol: 'L', country: 'Moldova'),
  'MGA': Currency(name: 'Malagasy Ariary', symbol: 'Ar', country: 'Madagascar'),
  'MKD': Currency(
    name: 'Macedonian Denar',
    symbol: 'ден',
    country: 'North Macedonia',
  ),
  'MMK': Currency(name: 'Burmese Kyat', symbol: 'Ks', country: 'Myanmar'),
  'MNT': Currency(name: 'Mongolian Tögrög', symbol: '₮', country: 'Mongolia'),
  'MOP': Currency(name: 'Macanese Pataca', symbol: 'P', country: 'Macau'),
  'MRU': Currency(
    name: 'Mauritanian Ouguiya',
    symbol: 'UM',
    country: 'Mauritania',
  ),
  'MUR': Currency(name: 'Mauritian Rupee', symbol: '₨', country: 'Mauritius'),
  'MVR': Currency(name: 'Maldivian Rufiyaa', symbol: '.ރ', country: 'Maldives'),
  'MWK': Currency(name: 'Malawian Kwacha', symbol: 'MK', country: 'Malawi'),
  'MXN': Currency(name: 'Mexican Peso', symbol: '\$', country: 'Mexico'),
  'MYR': Currency(name: 'Malaysian Ringgit', symbol: 'RM', country: 'Malaysia'),
  'MZN': Currency(
    name: 'Mozambican Metical',
    symbol: 'MT',
    country: 'Mozambique',
  ),
  'NAD': Currency(name: 'Namibian Dollar', symbol: '\$', country: 'Namibia'),
  'NGN': Currency(name: 'Nigerian Naira', symbol: '₦', country: 'Nigeria'),
  'NIO': Currency(
    name: 'Nicaraguan Córdoba',
    symbol: 'C\$',
    country: 'Nicaragua',
  ),
  'NOK': Currency(name: 'Norwegian Krone', symbol: 'kr', country: 'Norway'),
  'NPR': Currency(name: 'Nepalese Rupee', symbol: '₨', country: 'Nepal'),
  'NZD': Currency(
    name: 'New Zealand Dollar',
    symbol: '\$',
    country: 'New Zealand',
  ),
  'OMR': Currency(name: 'Omani Rial', symbol: 'ر.ع.', country: 'Oman'),
  'PAB': Currency(name: 'Panamanian Balboa', symbol: 'B/.', country: 'Panama'),
  'PEN': Currency(name: 'Peruvian Sol', symbol: 'S/', country: 'Peru'),
  'PGK': Currency(
    name: 'Papua New Guinean Kina',
    symbol: 'K',
    country: 'Papua New Guinea',
  ),
  'PHP': Currency(name: 'Philippine Peso', symbol: '₱', country: 'Philippines'),
  'PKR': Currency(name: 'Pakistani Rupee', symbol: '₨', country: 'Pakistan'),
  'PLN': Currency(name: 'Polish Złoty', symbol: 'zł', country: 'Poland'),
  'PYG': Currency(name: 'Paraguayan Guaraní', symbol: '₲', country: 'Paraguay'),
  'QAR': Currency(name: 'Qatari Riyal', symbol: 'ر.ق', country: 'Qatar'),
  'RON': Currency(name: 'Romanian Leu', symbol: 'lei', country: 'Romania'),
  'RSD': Currency(name: 'Serbian Dinar', symbol: 'дин.', country: 'Serbia'),
  'RUB': Currency(name: 'Russian Ruble', symbol: '₽', country: 'Russia'),
  'RWF': Currency(name: 'Rwandan Franc', symbol: 'Fr', country: 'Rwanda'),
  'SAR': Currency(name: 'Saudi Riyal', symbol: 'ر.س', country: 'Saudi Arabia'),
  'SBD': Currency(
    name: 'Solomon Islands Dollar',
    symbol: '\$',
    country: 'Solomon Islands',
  ),
  'SCR': Currency(
    name: 'Seychellois Rupee',
    symbol: '₨',
    country: 'Seychelles',
  ),
  'SDG': Currency(name: 'Sudanese Pound', symbol: 'ج.س.', country: 'Sudan'),
  'SEK': Currency(name: 'Swedish Krona', symbol: 'kr', country: 'Sweden'),
  'SGD': Currency(
    name: 'Singapore Dollar',
    symbol: 'S\$',
    country: 'Singapore',
  ),
  'SHP': Currency(
    name: 'Saint Helena Pound',
    symbol: '£',
    country: 'Saint Helena',
  ),
  'SLE': Currency(
    name: 'Sierra Leonean Leone',
    symbol: 'Le',
    country: 'Sierra Leone',
  ),
  'SOS': Currency(name: 'Somali Shilling', symbol: 'Sh', country: 'Somalia'),
  'SRD': Currency(name: 'Surinamese Dollar', symbol: '\$', country: 'Suriname'),
  'SSP': Currency(
    name: 'South Sudanese Pound',
    symbol: '£',
    country: 'South Sudan',
  ),
  'STN': Currency(
    name: 'São Tomé and Príncipe Dobra',
    symbol: 'Db',
    country: 'São Tomé and Príncipe',
  ),
  'SYP': Currency(name: 'Syrian Pound', symbol: '£', country: 'Syria'),
  'SZL': Currency(name: 'Eswatini Lilangeni', symbol: 'L', country: 'Eswatini'),
  'THB': Currency(name: 'Thai Baht', symbol: '฿', country: 'Thailand'),
  'TJS': Currency(
    name: 'Tajikistani Somoni',
    symbol: 'ЅМ',
    country: 'Tajikistan',
  ),
  'TMT': Currency(
    name: 'Turkmenistan Manat',
    symbol: 'm',
    country: 'Turkmenistan',
  ),
  'TND': Currency(name: 'Tunisian Dinar', symbol: 'د.ت', country: 'Tunisia'),
  'TOP': Currency(name: 'Tongan Paʻanga', symbol: 'T\$', country: 'Tonga'),
  'TRY': Currency(name: 'Turkish Lira', symbol: '₺', country: 'Turkey'),
  'TTD': Currency(
    name: 'Trinidad and Tobago Dollar',
    symbol: 'TT\$',
    country: 'Trinidad and Tobago',
  ),
  'TVD': Currency(name: 'Tuvaluan Dollar', symbol: '\$', country: 'Tuvalu'),
  'TWD': Currency(name: 'New Taiwan Dollar', symbol: 'NT\$', country: 'Taiwan'),
  'TZS': Currency(
    name: 'Tanzanian Shilling',
    symbol: 'Sh',
    country: 'Tanzania',
  ),
  'UAH': Currency(name: 'Ukrainian Hryvnia', symbol: '₴', country: 'Ukraine'),
  'UGX': Currency(name: 'Ugandan Shilling', symbol: 'Sh', country: 'Uganda'),
  'USD': Currency(
    name: 'United States Dollar',
    symbol: '\$',
    country: 'United States',
  ),
  'UYU': Currency(name: 'Uruguayan Peso', symbol: '\$U', country: 'Uruguay'),
  'UZS': Currency(
    name: 'Uzbekistani Soʻm',
    symbol: 'лв',
    country: 'Uzbekistan',
  ),
  'VES': Currency(
    name: 'Venezuelan Bolívar Soberano',
    symbol: 'Bs.',
    country: 'Venezuela',
  ),
  'VND': Currency(name: 'Vietnamese Đồng', symbol: '₫', country: 'Vietnam'),
  'VUV': Currency(name: 'Vanuatu Vatu', symbol: 'Vt', country: 'Vanuatu'),
  'WST': Currency(name: 'Samoan Tālā', symbol: 'T', country: 'Samoa'),
  'XAF': Currency(
    name: 'Central African CFA Franc',
    symbol: 'Fr',
    country: 'CEMAC',
  ),
  'XCD': Currency(
    name: 'East Caribbean Dollar',
    symbol: '\$',
    country: 'Organisation of Eastern Caribbean States',
  ),
  'XDR': Currency(
    name: 'Special Drawing Rights',
    symbol: 'SDR',
    country: 'International Monetary Fund',
  ),
  'XOF': Currency(name: 'West African CFA franc', symbol: 'Fr', country: 'CFA'),
  'XPF': Currency(
    name: 'CFP Franc',
    symbol: '₣',
    country: 'Collectivités d\'Outre-Mer',
  ),
  'YER': Currency(name: 'Yemeni Rial', symbol: '﷼', country: 'Yemen'),
  'ZAR': Currency(
    name: 'South African Rand',
    symbol: 'R',
    country: 'South Africa',
  ),
  'ZMW': Currency(name: 'Zambian Kwacha', symbol: 'ZK', country: 'Zambia'),
  'ZWL': Currency(name: 'Zimbabwean Dollar', symbol: '\$', country: 'Zimbabwe'),
};
